[package]
name = "test-faucet"
version = "1.0.0"
authors = []

[addresses]
test_faucet_addr = "_"

[dev-addresses]
test_faucet_addr = "0xface"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
